knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            redirect_route: login_github

        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            redirect_route: login_discord

        alliedmods:
            type: generic
            provider_class: App\Security\AlliedModdersOAuthProvider
            client_id: '%env(OAUTH_ALLIEDMODS_CLIENT_ID)%'
            client_secret: '%env(OAUTH_ALLIEDMODS_CLIENT_SECRET)%'
            redirect_route: login_alliedmods
