# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: 'Throttle'
    app.login_link_lifetime: 600

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Security\UserManager:
        arguments:
            $loginLinkLifetime: '%app.login_link_lifetime%'

    # this isn't quite correct, but it works for now
    App\Security\SteamOpenIdAuthenticator:
        arguments:
            $successHandler: '@security.authentication.success_handler.main.login_link'
            $failureHandler: '@security.authentication.failure_handler.main.login_link'
            $steamApiKey: '%env(STEAM_API_KEY)%'

    App\Security\GitHubOAuthAuthenticator:
        arguments:
            $successHandler: '@security.authentication.success_handler.main.login_link'
            $failureHandler: '@security.authentication.failure_handler.main.login_link'

    App\Security\DiscordOAuthAuthenticator:
        arguments:
            $successHandler: '@security.authentication.success_handler.main.login_link'
            $failureHandler: '@security.authentication.failure_handler.main.login_link'
